# Generated by Django 2.1.2 on 2018-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paypal_token',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
