# Generated by Django 2.1.2 on 2018-10-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_paypal_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paypal_token',
            field=models.CharField(blank=True, default='fake-paypal-billing-agreement-nonce', max_length=1024),
        ),
    ]
