# Generated by Django 2.1.2 on 2018-10-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='job',
        ),
        migrations.AddField(
            model_name='user',
            name='stars',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
