# Generated by Django 2.1.2 on 2018-10-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181021_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stars',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
