# Generated by Django 2.1.2 on 2018-10-21 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouch',
            name='vouching_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='credit.Loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='credit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='credit.Credit'),
        ),
        migrations.AddField(
            model_name='investment',
            name='credit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='credit.Credit'),
        ),
        migrations.AddField(
            model_name='investment',
            name='credit_impact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.CreditImpact'),
        ),
        migrations.AddField(
            model_name='investment',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments2', to='credit.Loan'),
        ),
        migrations.AddField(
            model_name='creditimpact',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_impacts', to='credit.Credit'),
        ),
        migrations.AddField(
            model_name='credit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to=settings.AUTH_USER_MODEL),
        ),
    ]
