# Generated by Django 2.1.2 on 2018-10-21 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_auto_20181021_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 10, 37, 19, 474893, tzinfo=utc), null=True),
        ),
    ]
