# Generated by Django 2.1.2 on 2018-10-21 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_auto_20181020_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investment',
            name='credit_impact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.CreditImpact'),
        ),
        migrations.AlterField(
            model_name='vouch',
            name='credit_impact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.CreditImpact'),
        ),
    ]
