# Generated by Django 2.1.2 on 2018-10-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_auto_20181021_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditimpact',
            name='source',
            field=models.CharField(blank=True, choices=[('LOAN', 'loan'), ('VOUCH', 'vouch'), ('EDU', 'education'), ('INVEST', 'investment'), ('BALANCE', 'balance')], max_length=12),
        ),
    ]
