# Generated by Django 2.1.2 on 2018-10-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_creditimpact_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditimpact',
            name='source',
            field=models.CharField(blank=True, choices=[('LOAN', 'loan'), ('VOUCH', 'vouch'), ('EDUCATION', 'education'), ('INVESTMENT', 'investment'), ('BALANCE', 'balance')], max_length=12),
        ),
    ]
