# Generated by Django 2.1.2 on 2018-10-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
