# Generated by Django 2.1.2 on 2018-10-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_auto_20181021_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
