# Generated by Django 2.1.2 on 2018-10-21 02:57

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_loan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouch',
            name='status',
            field=models.CharField(choices=[('INVITED', 'invited'), ('ACCEPTED', 'accepted'), ('DECLINED', 'declined')], default='invited', max_length=12),
        ),
        migrations.AlterField(
            model_name='vouch',
            name='amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19),
        ),
    ]
