# Generated by Django 2.1.2 on 2018-10-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0011_auto_20181021_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
