# Generated by Django 2.1.2 on 2018-10-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0012_loan_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vouch',
            old_name='user',
            new_name='vouching_user',
        ),
    ]
