# Generated by Django 2.1.2 on 2018-10-21 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0013_auto_20181021_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouch',
            name='vouching_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
