# Generated by Django 2.1.2 on 2018-10-21 05:31

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0015_auto_20181021_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouch',
            name='amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('20.00'), default_currency='USD', max_digits=19),
        ),
    ]
